POST http://192.168.2.112:9002/portal/admin/login
Content-Type: application/json;charset=UTF-8

{"username": "u.polder@nakamilounge.de", "password": "Hawaii11"}


OPTIONS http://192.168.2.112:9002/portal/admin/login
Content-Type: application/json;charset=UTF-8

{"username": "u.polder@nakamilounge.de", "password": "Hawaii11"}